version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports: 
      - "9000:80"
    volumes: 
      - ./utils/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    environment: 
      - PORT=9000
    depends_on: 
      - mongo

  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=tony
      - MONGO_INITDB_ROOT_PASSWORD=123123
    volumes: 
      - mongo-db:/data/db

  redis:
    image: redis
    
volumes: 
  mongo-db: