version: "3"
services:
  nginx:
    ports: 
      - "9000:80"

  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes: 
      - ./:/app:ro
      - /app/node_modules
    environment:  
      - MONGO_USER=tony
      - MONGO_PASSWORD=123123
      - SESSION_SECRET=secret

    command: npm run dev

  mongo:xs
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=tony
      - MONGO_INITDB_ROOT_PASSWORD=123123
  