version: "3"
services:
  whatsapp-backend:
    build: .
    ports: 
      - "9000:9000"
    environment: 
      - PORT=9000
    depends_on: 
      - mongo

  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=tony
      - MONGO_INITDB_ROOT_PASSWORD=123123
    volumes: 
      - mongo-db:/data/db

volumes: 
  mongo-db: