version: "3"
services:
  whatsapp-backend:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes: 
      - ./:/app:ro
      - /app/node_modules
    environment: 
      - MONGO_USER=tony
      - MONGO_PASSWORD=123123
    command: npm run dev

  mongo:
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=tony
      - MONGO_INITDB_ROOT_PASSWORD=123123